services:
  app-play-1:
    build:
      context: .
      args:
        PROFILE: PLAYER
      dockerfile: ./Dockerfiles/queue-application/Dockerfile
    networks:
      - rabbitPoc
  app-play-2:
    build:
      context: .
      args:
        PROFILE: PLAYER
      dockerfile: Dockerfiles/queue-application/Dockerfile
    networks:
      - rabbitPoc
  app-dealer:
    build:
      context: .
      args:
        PROFILE: DEALER
      dockerfile: Dockerfiles/queue-application/Dockerfile
    networks:
      - rabbitPoc

  rabit-mq-1:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
    networks:
      - rabbitPoc

networks:
  rabbitPoc:
    driver: bridge