services:
  app-push:
    build:
      context: .
      args:
        PROFILE: PUSH
      dockerfile: ./Dockerfiles/queue-application/Dockerfile
    networks:
      - rabbitPoc

  app-pull:
    build:
      context: .
      args:
        PROFILE: PULL
      dockerfile: Dockerfiles/queue-application/Dockerfile
    networks:
      - rabbitPoc

  rabit-mq-1:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
    networks:
      - rabbitPoc

networks:
  rabbitPoc:
    driver: bridge