services:
  rabit-mq-1:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
    networks:
      - rabbitPoc
  mongodb:
    image: mongo:jammy
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - rabbitPoc
  mongo-express:
    image: mongo-express:1.0.2-18
    restart: always
    ports:
      - 8081:8081
    networks:
      - rabbitPoc
  app-play-1:
    ports:
      - 8080:8080
      - 27016:27017
    depends_on:
      - mongodb
      - rabit-mq-1
    build:
      context: .
      args:
        PROFILE: SPRING
      dockerfile: ./Dockerfiles/queue-application/Dockerfile
    networks:
      - rabbitPoc
networks:
  rabbitPoc:
    driver: bridge